### ISSUE TITLE
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "widget_configurations" does not exist LINE 1: select * from "widget_configurations" where "dashboard" = $1... ^ (SQL: select * from "widget_configurations" where "dashboard" = custom-dashboard-1 and "view" = view-1-default and "key" in (visual-1, visual-2))

### ISSUE THREAD

**Issue by xoco70** [Nova-BI/nova-dashboard-manager#1]
Hi, 

I tried to install the plugin, 

I can migrate tables, create a filter, a widget, a dashboard.

When trying to access to the dashboard, I get this error:

`SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "widget_configurations" does not exist LINE 1: select * from "widget_configurations" where "dashboard" = $1... ^ (SQL: select * from "widget_configurations" where "dashboard" = custom-dashboard-1 and "view" = view-1-default and "key" in (visual-1, visual-2))`

I guess it hasn't been migrated.

**Comment by cord** [comment]
did you publish the config files?

**Comment by xoco70** [comment]
yep. but no widget_configurations table in DB. There is only 9 migrations.

**Comment by cord** [comment]
the migration files for widgets and widgets_configurations are defined in
https://github.com/dcasia/nova-dashboard

can you check if you get an error for that migration?

**Comment by xoco70** [comment]
Yes, it gave me an error about widget table. I had to delete it manually. But I can't see any widgets_configurations migration in https://github.com/dcasia/nova-dashboard. Any particular branch ?

**Comment by cord** [comment]
you are right, the "widgets_configuration" is "widgets" in https://github.com/dcasia/nova-dashboard.

the table name is set in the config files of this package. so when you already had installed nova-dashboard then you either need to change the configuration or rename the table or rollback and migrate after adding this package.
