### ISSUE TITLE
I cannot install the dashboard

### ISSUE THREAD

**Issue by VasilePintilie** [Nova-BI/nova-dashboard-manager#11]
Using `composer require nova-bi/nova-dashboard-manager`, I get the following error

`Problem 1
    - Root composer.json requires nova-bi/nova-dashboard-manager ^1.5 -> satisfiable by nova-bi/nova-dashboard-manager[1.5].
    - nova-bi/nova-dashboard-manager 1.5 requires digital-creative/nova-inline-morph-to dev-custom -> found digital-creative/nova-inline-morph-to[dev-dependabot/npm_and_yarn/ini-1.3.8, dev-dependabot/npm_and_yarn/lodash-4.17.21, dev-dependabot/npm_and_yarn/ssri-6.0.2, dev-dependabot/npm_and_yarn/elliptic-6.5.4, dev-dependabot/npm_and_yarn/y18n-4.0.1, dev-dependabot/npm_and_yarn/dns-packet-1.3.4, dev-dependabot/npm_and_yarn/url-parse-1.5.1, dev-dependabot/npm_and_yarn/axios-0.21.1, dev-dependabot/npm_and_yarn/browserslist-4.16.6, dev-master, v0.1.0, ..., v0.2.1] but it does not match the constraint.`

**Comment by marispro** [comment]
Hello,

fixed in newest release. 

Thank you for reporting!

**Comment by danielaWaldeck95** [comment]
Hi! Using composer require nova-bi/nova-dashboard-manager I get the following error:

 Problem 1
    - Root composer.json requires nova-bi/nova-dashboard-manager ^3.0 -> satisfiable by nova-bi/nova-dashboard-manager[3.0].
    - nova-bi/nova-dashboard-manager 3.0 requires eminiarts/nova-tabs ^1.0 -> found eminiarts/nova-tabs[1.0.0, ..., v1.x-dev] but it conflicts with your root composer.json require (^2.1).

I've already tried with the option --with-all-dependencies (-W)

**Comment by marispro** [comment]
Hello @danielaWaldeck95 .
Seems you are using eminiarts/nova-tabs v2, but this is supported only in Nova 4.
This package is supported only with nova 3, so eminiarts/nova-tabs v1 only allowed.
