### ISSUE TITLE
Redirection after create dashboard

### ISSUE THREAD

**Issue by MarcosGit** [Nova-BI/nova-dashboard-manager#12]
Hi, first thanks for this greate work.

when i create new dashboard its redirect to http://resources/dashboard-configuration when it should redirect to http://127.0.0.1:8000/resources/dashboard-configuration

I dont know why if i make mistake or its package issue.

**Comment by marispro** [comment]
Hi Marcos,

this is how redirect url is generated:
`return '/redirectAfter?to=' . url( Nova::path() . '/resources/' . static::uriKey());`

what path variable value do you have in file config/nova.php ?

**Comment by MarcosGit** [comment]
Ok, thats happens because i change my Nova app to go direct to admin.
I changed this path
'path' => '/nova',
to this
'path' => '/',

**Comment by marispro** [comment]
It seems double slash causes this issue,
what happens if you set `'path' => '',` ?

**Comment by MarcosGit** [comment]
Yes thats the problem i remove the slash and all is work great.
Thank you for you time and help
