### ISSUE TITLE
App\User not found when using User example

### ISSUE THREAD

**Issue by xoco70** [Nova-BI/nova-dashboard-manager#2]
With Laravel 8, User model is in `App\Models\Users`, but you're expecting `App\Users`

it should be possible to set it in config file

**Comment by cord** [comment]
@marispro can you check?

**Comment by marispro** [comment]
Added option to set model in config file:
https://github.com/Nova-BI/nova-dashboard-manager/releases/tag/0.5

Need to re-publish configuration:
``php artisan vendor:publish --provider="NovaBi\NovaDashboardManager\DashboardManagerServiceProvider" --tag="config"``

By default user models is set to `App\Models\Users`
