### ISSUE TITLE
support optimistdigital/nova-sortable 2.0

### ISSUE THREAD

**Issue by cord** [Nova-BI/nova-dashboard-manager#6]
composer says:

`nova-bi/nova-dashboard-manager dev-main requires optimistdigital/nova-sortable ^1.0 -> found optimistdigital/nova-sortable[1.0.0, ..., 1.6.2] but it conflicts with your root composer.json require (^2.0) `

**Comment by marispro** [comment]
Updated https://github.com/Nova-BI/nova-dashboard-manager/commit/da7ee5250225b09cf7207be6cbcc1f756f207efb
