### ISSUE TITLE
Widgets section don't work after update

### ISSUE THREAD

**Issue by keizah7** [Nova-BI/nova-dashboard-manager#9]
Method DigitalCreative\InlineMorphTo\InlineMorphTo::typeUpdateable does not exist.

**Comment by mdanro** [comment]
Comment it out and will launch, however it depends on some fixed paths to the Models

**Comment by keizah7** [comment]
I don't use this method by myself, it's package error

**Comment by keizah7** [comment]
I don't use this method by myself, it's package error #10

**Comment by marispro** [comment]
This is related to https://github.com/dcasia/nova-inline-morph-to/pull/25 where we added typeUpdateable method to allow update model data after creation.
While pull request is not approved, we are using fork https://github.com/marispro/nova-inline-morph-to

Currently, we have this dependency attached through repositories: https://github.com/Nova-BI/nova-dashboard-manager/blob/main/composer.json
![image](https://user-images.githubusercontent.com/5610414/112613556-85cf8700-8e20-11eb-86ec-d15fb9d6f9a7.png)

But it is strange, that this dependency is not applied for you.
Do you have "digital-creative/nova-inline-morph-to" package in your composer.json?

**Comment by mdanro** [comment]
I can confirm that the dependency exists but it is not applied, this is composer.json
`{
    "name": "nova-bi/nova-dashboard-manager",
    "description": "Create and manage dynamic dashboards",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "nova-bi",
            "email": "novabi@mailbeez.com"
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=7.4.0",
        "davidpiesse/nova-toggle": "^0.0.8",
        "digital-creative/nova-dashboard": "dev-master",
        "digital-creative/nova-inline-morph-to": "dev-master",
        "digital-creative/nova-data-table": "^0.1.1",
        "digital-creative/nova-pill-filter":"dev-master",
        "digital-creative/nova-range-input-filter": "dev-master",
        "digital-creative/value-widget": "dev-master",
        "digitalazgroup/nova-plain-text-field": "^0.0.4",
        "digital-creative/chartjs-widget": "dev-master",
        "dillingham/nova-attach-many": "^1.0",
        "dillingham/nova-detail-link": "^1.0",
        "eminiarts/nova-relationship-selector": "^1.0",
        "eminiarts/nova-tabs": "^1.0",
        "epartment/nova-dependency-container": "^1.2.10",
        "ericlagarda/nova-text-card": "^1.2",
        "klepak/nova-multiselect-filter": "^1.2",
        "laramaker/redirect-after-asset": "^1.0",
        "optimistdigital/nova-sortable": "^2.0",
        "pdmfc/nova-info-card": "^1.0",
        "rcknr/nova-multiselect-filter": "^1.3",
        "spatie/laravel-schemaless-attributes": "^1.5"
    },
    "extra": {
        "laravel": {
            "providers": [
                "NovaBi\\NovaDashboardManager\\DashboardManagerServiceProvider"
            ]
        }
    },
    "autoload": {
        "psr-4": {
            "NovaBi\\NovaDashboardManager\\": "src/"
        }
    },
    "config": {
        "sort-packages": true
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:marispro/nova-inline-morph-to.git"
        } 
    ]
}
`

**Comment by mdanro** [comment]
I can confirm that the dependency exists but probably ignored:
        "digital-creative/nova-inline-morph-to": "dev-master",

    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:marispro/nova-inline-morph-to.git"
        }

**Comment by keizah7** [comment]
@marispro
```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/marispro/nova-inline-morph-to"
    }
]
```
I think you should create custom branch in `marispro/nova-inline-morph-to`
And require it like this
`"digital-creative/nova-inline-morph-to": "dev-custom",`
Original package also has master branch, so maybe conflict is here

**Comment by marispro** [comment]
@keizah7  thanks! Changed branch to dev-custom and updated dependecies on composer. Can you try update composer and look does it solve the problem?

**Comment by keizah7** [comment]
@marispro problem still appears

**Comment by keizah7** [comment]
```
Problem 1
    - Installation request for nova-bi/nova-dashboard-manager ^1.3 -> satisfiable by nova-bi/nova-dashboard-manager[1.3].
    - nova-bi/nova-dashboard-manager 1.3 requires digital-creative/nova-inline-morph-to dev-custom -> no matching package found.

```

**Comment by marispro** [comment]
Renamed branch from "custom" to "dev-custom", probably requires some time to drop composer cache or `composer clearcache`

**Comment by keizah7** [comment]
It should work if your branch named custom. custom => dev-custom. if your branch dev-custom, you should required dev-dev-custom..
You didn't changed repository url, maybe problem is here

**Comment by marispro** [comment]
@keizah7 Ok didn't know that. Changed back to custom. 
Custom is only branch here https://github.com/marispro/nova-inline-morph-to (renamed from master).
What url need to be changed? 

Thank you for help!

**Comment by keizah7** [comment]
```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/marispro/nova-inline-morph-to"
    }
]
```
Try this one

**Comment by marispro** [comment]
> ```
> "repositories": [
>     {
>         "type": "vcs",
>         "url": "https://github.com/marispro/nova-inline-morph-to"
>     }
> ]
> ```
> 
> Try this one

Changed

**Comment by keizah7** [comment]
https://packagist.org/packages/nova-bi/nova-dashboard-manager
where is v1.4?

**Comment by keizah7** [comment]
```
 Problem 1
    - Installation request for nova-bi/nova-dashboard-manager ^1.4 -> satisfiable by nova-bi/nova-dashboard-manager[1.4].
    - nova-bi/nova-dashboard-manager 1.4 requires digital-creative/nova-inline-morph-to dev-custom -> no matching package found.

```

**Comment by mdanro** [comment]
I have the same issue
composer update nova-bi/nova-dashboard-manager --with-all-dependencies

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nova-bi/nova-dashboard-manager ^1.4 -> satisfiable by nova-bi/nova-dashboard-manager[1.4].
    - nova-bi/nova-dashboard-manager 1.4 requires digital-creative/nova-inline-morph-to dev-custom -> found digital-creative/nova-inline-morph-to[dev-dependabot/npm_and_yarn/ini-1.3.8, dev-dependabot/npm_and_yarn/elliptic-6.5.4, dev-dependabot/npm_and_yarn/axios-0.21.1, dev-master, v0.1.0, ..., v0.2.1] but it d
oes not match the constraint.

**Comment by keizah7** [comment]
@mdanro 

```
{
  "require": {
       "nova-bi/nova-dashboard-manager": "dev-main",
  }
  "repositories": [
       {
           "type": "vcs",
            "url": "https://github.com/keizah7/nova-dashboard-manager"
       }
  ]
}
```

``composer update``
